Precalculus EQ7 Checkit
TeamBasedInquiryLearning/library pull request #216
Opened 2024-08-02 22:29 UTC by siwelwerd

Closes #187

2024-08-07 21:26 UTC, siwelwerd commented
Okay, finished Task 2.  Now to handle Task 1 🥵

2024-08-07 22:33 UTC, siwelwerd commented
This could probably be refactored to be nicer, but I am tired of it and there are plenty of other things to work on now.  It seems to do what we want it to do though, so marking this ready.

2024-08-23 21:16 UTC, StevenClontz commented
![image](https://github.com/user-attachments/assets/3ee3a88a-49fc-41b1-9038-3798b993d1cd)

Something is goofy, I don't think 0 is a solution to either inequality?

2024-08-23 21:16 UTC, StevenClontz requested changes
see recent comment

2024-08-23 21:18 UTC, siwelwerd commented
Might just be a backwards inequality, so hopefully an easy fix.

2024-08-23 22:16 UTC, siwelwerd commented on source/precalculus/sage/common.sage
> +        if operator == '>': return LHS < RHS
>
```suggestion
        if operator == '<': return LHS < RHS
        if operator == '>': return LHS > RHS
```

2024-08-23 22:17 UTC, siwelwerd commented on source/precalculus/sage/common.sage
> +        if operator == '>': return LHS < RHS
Pretty sure this will fix the issue @StevenClontz spotted, but this should probably just be refactored along the lines of #257

2024-08-24 00:00 UTC, siwelwerd commented
I refactored this to use Sage inequalities.  I was basically using the same code twice to generate intervals for the solutions, so I factored that into a helper function in common.sage.  This makes it much clearer to read.   I also managed to catch a divide-by-zero error and fix that too.

2024-08-24 00:03 UTC, siwelwerd commented on source/precalculus/exercises/outcomes/EQ/EQ7/generator.sage
> +      rational_inequality = LHS >= RHS
I couldn't see a clean way to use `CheckIt.shuffled_inequality()` here, as all I have to play with are two rational functions, and I just want $P(x)<Q(x)$ or similar. The `shuffled_inequality()` kept doing silly things like $P(x)+Q(x)>0 $which I didn't want.

2024-08-26 15:51 UTC, siwelwerd commented on source/precalculus/exercises/outcomes/EQ/EQ7/generator.sage
> +      rational_inequality = LHS >= RHS
After stewing on this over the weekend, thought up a cleaner fix implemented in [ac06620](https://github.com/TeamBasedInquiryLearning/library/pull/216/commits/ac0662031f5bb64b7191cbbb589ee77c321cf1dd) using the `operator` module.

2024-08-26 16:28 UTC, StevenClontz approved these changes

2024-08-26 16:28 UTC, merged