Clarify unknowns in AT-ready
TeamBasedInquiryLearning/library pull request #355
Opened 2024-10-11 19:24 UTC by StevenClontz

Ensures that when a set is a basis, "linearly independent" and "spanning" by themselves are not also correct answers.

2024-10-11 19:54 UTC, jkostiuk requested changes
linearlly->linearly 

(can you remind how to make edit-suggestions properly? I think there's a way for me to just edit and then for you to accept/reject?)

2024-10-11 20:43 UTC, StevenClontz commented
![image](https://github.com/user-attachments/assets/7910a131-26c2-4074-b4a9-3186b5eb13df)

2024-10-11 20:55 UTC, jkostiuk commented on source/linear-algebra/exercises/outcomes/AT/AT-ready/template.xml
> +                <item><p>(c) <m>S</m> spans <m>\mathbb R^{ {{dim}} }</m>, but we cannot tell if it is linearlly independent.</p></item>
```suggestion
                <item><p>(c) <m>S</m> spans <m>\mathbb R^{ {{dim}} }</m>, but we cannot tell if it is linearly independent.</p></item>
```

2024-10-11 20:56 UTC, jkostiuk commented on source/linear-algebra/exercises/outcomes/AT/AT-ready/template.xml
> +                <p>(c) <m>S</m> spans <m>\mathbb R^{ {{dim}} }</m>, but we cannot tell if it is linearlly independent.</p>
```suggestion
                <p>(c) <m>S</m> spans <m>\mathbb R^{ {{dim}} }</m>, but we cannot tell if it is linearly independent.</p>
```

2024-10-14 16:20 UTC, jford1906 approved these changes

2024-10-14 16:21 UTC, jford1906 approved these changes

2024-10-14 16:21 UTC, jford1906 commented
I thought I approved all of the changes, but Merging is still blocked

2024-10-14 18:31 UTC, jkostiuk approved these changes

2024-10-14 18:39 UTC, merged