Sage images for TI and AI
TeamBasedInquiryLearning/library pull request #461
Opened 2024-12-16 20:08 UTC by cg2wilson

Added sage images for TI and AI

2025-02-20 21:40 UTC, jbunn3 requested changes
Hi Cory, Wow! you do a ton of work getting these plots done. They look great! I did have quite a few suggestions, so please update as you see fit. I'll be glad to revisit them again after you decide whether to make any changes.

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/07.ptx
> +                        </sageplot>
The plot looks great to me. (I do plan on creating an issue on this section at some point, because I feel like it is quite underdeveloped.)

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/05.ptx
> +                        label_1 = text('$h_1 = 0$ m',(-.6,0),color='black',fontsize=12)
I would maybe consider a larger font size on the labels.

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/05.ptx
> +                        rad2 = text('$r_2$',(.5,3.75),color='black',fontsize=10)
I guess you need these radii to have smaller font sizes due to space, but they do look a little strange relative to the height labels.

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/05.ptx
> +                        xaxis = arrow((-1,0),(5,0),thickness=1,color='black')
```suggestion
                        xaxis = arrow((-1,0),(5,0),width=1,color='black')
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/05.ptx
> +                        xaxis = arrow((-1,0),(5,0),thickness=1,color='black')
I like having the thicker bounds on the solid and a thinner axis, as you had, but the command for arrow is evidently width and not thickness.

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/05.ptx
> +                        </sageplot>
All of the rest of the plots look great!

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        side_label = text('$\\Delta h = 5$ in', (-0.5,3),color='black',fontsize=13)
```suggestion
                        side_label = text('$\\Delta h = 5$ m', (-0.5,3),color='black',fontsize=13)
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        side_label1 = text('$\\Delta h = 5$ in', (-0.5,1),color='black',fontsize=13)
```suggestion
                        side_label1 = text('$\\Delta h = 5$ m', (-0.5,1),color='black',fontsize=13)
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        side_label2 = text('$\\Delta h = 5$ in', (-0.5,3),color='black',fontsize=13)
```suggestion
                        side_label2 = text('$\\Delta h = 5$ m', (-0.5,3),color='black',fontsize=13)
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        side_label3 = text('$\\Delta h = 5$ in', (-0.5,5),color='black',fontsize=13)
```suggestion
                        side_label3 = text('$\\Delta h = 5$ m', (-0.5,5),color='black',fontsize=13)
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        side_label4 = text('$\\Delta h = 5$ in', (-0.5,7),color='black',fontsize=13)
```suggestion
                        side_label4 = text('$\\Delta h = 5$ m', (-0.5,7),color='black',fontsize=13)
```

2025-02-20 21:40 UTC, jbunn3 commented on source/calculus/source/06-AI/06.ptx
> +                        </sageplot>
Beautiful plot!

2025-02-20 21:59 UTC, cg2wilson commented on source/calculus/source/06-AI/01.ptx
> +                        </sageplot>
easy enough to fix! i added a dummy plot to extend the y-axis length.

2025-02-21 00:37 UTC, jbunn3 reviewed
All looks good to me now.

2025-02-21 00:38 UTC, merged