Add scaffolding and reorder exercises
TeamBasedInquiryLearning/library pull request #462
Opened 2024-12-16 20:40 UTC by daverosoff

This addresses issue #54.

2024-12-16 23:03 UTC, StevenClontz reviewed
New activity: [Activity 5.1.13](https://177cbb93.tbil.pages.dev/preview/calculus/instructor/TI1#TI1-3-14)

Existing activity: [Activity 5.1.9](https://library.tbil.org/2024/calculus/TI1.html#TI1-3-10)

I agree with @AbbyANoble's note in #54 that the side-by-side squeezes things a bit together, and that moving the activity to later in the section might be better, after students have seen some more examples.

However, I'm unsure I like all the commentary being added here. When I wrote the activity, I wanted students to see two clean, correct writeups to help them build fluency in how to work though a substitution problem, and it's a mix of instructor facilitation and student inquiry to break down each step of the two writeups.

I'd propose making task (a) the first writeup (the left panel of the original sidebyside), with an MCQ asking if it was a valid solution or not. Then task (b) asks the same of the second writeup (the right sidebyside panel). Then task (c) asks students to justify why both solutions are correct.

2024-12-17 00:35 UTC, daverosoff commented
OK, is there a way I should have known to ignore the part of #54 about "more scaffolding" but pay attention to the rest? Thanks.

2024-12-17 03:39 UTC, StevenClontz commented
Not without having a discussion. :-/ Speaking of which, @AbbyANoble should chime in with her opinion.

2024-12-17 21:51 UTC, jbunn3 commented
I looked over the suggested changes here and discussion, and I think having this a bit later is a good call. I'm not so sure I think this problem would need scaffolding at this point of the section, as by the time it surfaces, I would expect the students to have gained some experience in choosing the substitution. However, it did appear to be a bit too early in the previous version. 

I would suggest keeping the new ordering, but itemizing the two original, clean write-up so that they appear one after the other. Then, I would keep part (c) where they analyze the different representations of the solution. 

(To be honest, I'm not a big fan of having the u-sub work in a second column, although that's how many people do it.)

2024-12-18 00:37 UTC, StevenClontz requested changes
See above recommended changes.

2024-12-18 16:17 UTC, AbbyANoble commented
I think the scaffolding is helpful here because, even though it's moved down, it's still the first time they see a "weird" choice for u. It's really the only time in the whole sections where the u is somewhat unexpected. @StevenClontz I get what you mean about leaving it like you had it to help with fluency, but if there is no example of this happening before (with at least some scaffolding), I think the fluency part is very hard to catch on to by just looking at it for an average calc student at this point. @daverosoff's adds in the thought process behind it, which I like. 

I'd move this to the very end of the section, though, then add a couple fluency problems that have this similar idea of unexpected substitutions.

Then I'd move [Activity 5.1.21](https://177cbb93.tbil.pages.dev/preview/calculus/instructor/TI1#TI1-3-22) (shown below) after that, probably with making the variable something other than u. (I know it doesn't really matter, but trying a new type where the variable is the one you usually use to substitute seems like adding in unnecessary complexity.) The way I did this one I chose the "expected" u or x^3+1, but then you have to fiddle around to substitute everything else in a way that hasn't happened before in the activities. (Unless I'm missing something.)

<img width="623" alt="Screenshot 2024-12-18 at 11 08 13 AM" src="https://github.com/user-attachments/assets/0cbfeaf8-11ed-48ed-8c42-19afcc141537" />

Then some fluency with these as well. Or maybe put this example right after @daverosoff's and do one fluency set of the unexpected substitutions.

2025-05-19 17:18 UTC, closed without merging

2025-05-19 17:18 UTC, daverosoff commented
Looks like I didn't actually finish this. I feel silly. Anyway, this branch is too old to be convenient—I'll start a fresh one and work on the changes requested above.