Creating PS 5 on Taylor's Theorem
TeamBasedInquiryLearning/library pull request #497
Opened 2024-12-18 18:16 UTC by jbunn3

This is the beginning stages of creating the section P5, starting from a sample problem, a learning outcome, and some introduction.

2024-12-20 20:49 UTC, cg2wilson requested changes
Most of what I saw are small formatting/consistency things. The substance of it all looks great to me!

2024-12-20 20:49 UTC, cg2wilson commented on source/calculus/source/09-PS/05.ptx
> +
I think the answer choices are meant to be $R_2(4)$ and $R_3(4)$

2024-12-20 20:49 UTC, cg2wilson commented on source/calculus/source/09-PS/05.ptx
> +    </theorem>
Should the centering term be $x-c$ to be consistent with what's written in Fact 9.5.4?

2024-12-20 20:49 UTC, cg2wilson commented on source/calculus/source/09-PS/05.ptx
> +                </ol>
I think the fourth derivative notation should be consistent; I think $f^{(4)}(x)$ looks better than $f^{''''}(x)$, but it doesn't matter which is used, I don't think.

2025-01-13 17:58 UTC, jbunn3 commented on source/calculus/source/09-PS/05.ptx
> +
Thanks, I made the updates.

2025-01-13 18:00 UTC, jbunn3 commented on source/calculus/source/09-PS/05.ptx
> +    </theorem>
Good point. It has been updated.

2025-01-13 18:02 UTC, jbunn3 commented on source/calculus/source/09-PS/05.ptx
> +                </ol>
I had thought about but just left it. I agree keeping it consistent is better. It's updated.

2025-01-13 19:34 UTC, cg2wilson approved these changes

2025-01-13 19:35 UTC, merged